-- Migration: Create suggestion_history table for Auto-DJ V3
-- This table tracks all suggestions generated by the AI, whether they were played,
-- and helps prevent suggestion repetition and improve personalization.

-- Create the suggestion_history table
CREATE TABLE IF NOT EXISTS suggestion_history (
  id BIGSERIAL PRIMARY KEY,
  spotify_track_id TEXT NOT NULL,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('safe', 'build', 'bold')),
  
  -- Tracking
  suggested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  was_played BOOLEAN NOT NULL DEFAULT FALSE,
  generation_id TEXT, -- Group multiple suggestions from same generation
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_suggestion_history_suggested_at
  ON suggestion_history(suggested_at DESC);

CREATE INDEX IF NOT EXISTS idx_suggestion_history_track_id
  ON suggestion_history(spotify_track_id);

CREATE INDEX IF NOT EXISTS idx_suggestion_history_generation_id
  ON suggestion_history(generation_id);

CREATE INDEX IF NOT EXISTS idx_suggestion_history_artist
  ON suggestion_history(artist);

CREATE INDEX IF NOT EXISTS idx_suggestion_history_was_played
  ON suggestion_history(was_played);

CREATE INDEX IF NOT EXISTS idx_suggestion_history_suggested_at_was_played
  ON suggestion_history(suggested_at DESC, was_played);

-- RLS Policies
ALTER TABLE suggestion_history ENABLE ROW LEVEL SECURITY;

-- Policy 1: Admin can read all suggestions
CREATE POLICY "Admin can read all suggestion history"
  ON suggestion_history
  FOR SELECT
  USING (true);

-- Policy 2: Only authenticated users (DJ admin) can insert suggestions
CREATE POLICY "DJ admin can insert suggestions"
  ON suggestion_history
  FOR INSERT
  WITH CHECK (true);

-- Policy 3: Only authenticated users can update was_played
CREATE POLICY "DJ admin can mark suggestions as played"
  ON suggestion_history
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- Helper function to mark a track as played from suggestion_history
CREATE OR REPLACE FUNCTION mark_suggestion_as_played(
  p_spotify_track_id TEXT,
  p_limit INT DEFAULT 1
)
RETURNS INT AS $$
DECLARE
  v_updated INT;
BEGIN
  UPDATE suggestion_history
  SET was_played = TRUE
  WHERE spotify_track_id = p_spotify_track_id
    AND was_played = FALSE
    AND suggested_at > NOW() - INTERVAL '24 hours'
  LIMIT p_limit;
  
  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated;
END;
$$ LANGUAGE plpgsql;

-- Helper function to get recent suggestion stats
CREATE OR REPLACE FUNCTION get_suggestion_stats(
  p_days INT DEFAULT 1
)
RETURNS TABLE(
  spotify_track_id TEXT,
  title TEXT,
  artist TEXT,
  total_suggestions INT,
  times_played INT,
  play_rate NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    sh.spotify_track_id,
    sh.title,
    sh.artist,
    COUNT(*)::INT as total_suggestions,
    COUNT(*) FILTER (WHERE sh.was_played)::INT as times_played,
    ROUND(COUNT(*) FILTER (WHERE sh.was_played)::NUMERIC / COUNT(*)::NUMERIC, 3) as play_rate
  FROM suggestion_history sh
  WHERE sh.suggested_at > NOW() - (p_days || ' days')::INTERVAL
  GROUP BY sh.spotify_track_id, sh.title, sh.artist
  ORDER BY total_suggestions DESC;
END;
$$ LANGUAGE plpgsql;
